name: moopopup
author: abidibo
category: Interface
tags: [window, ui, layer, popup]
docs: http://www.abidibo.net/projects/js/moopopup
demo: http://www.abidibo.net/projects/js/moopopup/demo
current: 0.2.5
